version: '3.7'
services:
  node-server-container:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - ./server:/app
    ports:
      - '3000:3000'
  web-app-container:
    build:
      context: ./byte-bank-broker
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./byte-bank-broker:/app
    ports:
      - '4200:4200'
    depends_on:
      - node-server-container
